#!/usr/bin/python3

import sys
import inspect
from itertools import product
from typing import Callable 

if len(sys.argv) < 2:
    print(">>> table \"lambda ...: True\"")
    exit(0)

func: Callable = eval(sys.argv[1])
args = inspect.getfullargspec(func).args 
print(args)

args_name = ', '.join(list(map(lambda x: f"[{x}]", args)))
res = []

for i in product([0, 1], repeat=len(args)):
    res += list(i) + [func(*i)]

res = ', '.join(list(map(lambda x: f"[{x}]", res)))

table = f"""
#table(
    columns: {len(args) + 1},
    stroke: 0.5pt,
    align: center+ horizon,
    {args_name}, [f = {sys.argv[1].split(':')[-1].strip()}],
    {res}
)
"""

print(table)
